sudo: false
language: python
python:
  - "3.4"
install:
  - "pip install -r requirements/dev.txt"
  - pip install coveralls==0.4.4
env:
  secure: "MU+x68snHYqrm/aYHgdJcutZoTiRo1sl4MU8K09GfMp/Y4s6McNllqLheg8hM6MZAlQcOTPyp/kE8nr8cneYExl0tvH4yU6gVIZj9C7oOYJm4Qx++uNRlevbQ2Yo1lkHZnL8iNlXvqsOzxrB9ryxNClyc/M4OS6fQuyXzYcC/Fg="
before_script:
  - psql -c "CREATE DATABASE systersdb;" -U carol
script:
  - coverage run vms/manage.py test --settings=vms.settings_carol
  - flake8 vms
after_success:
  coveralls --rcfile=.coveragerc
